[package]
name = "raspdac-display"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "raspdac-display"
path = "src/main.rs"

[[bin]]
name = "check-oled"
path = "bin/check_oled.rs"

[[bin]]
name = "ocpp-server-simu"
path = "bin/ocpp_server_simu.rs"

[dependencies]
tokio = { version = "1", features = ["sync", "macros", "rt", "signal", "time"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
rpi-pal = "0.22"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.229", features = ["serde_derive"] }
serde_json = "1.0.151"
futures-lite = { version = "2.6.1", default-features = false }

[features]
default = []
simu = []

[profile.release-slim]
inherits = "release"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1
